ClientDashboard-Integrated/ClientDashboard/ClientDashboard/ClientDashboard/Models/Client.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int ClientID { get; set; }
        public string Name { get; set; }
        public string ImagePath { get; set; }
        public string Website { get; set; }
    
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}

ClientDashboard-Integrated/ClientDashboard/ClientDashboard/ClientDashboard/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClientDashboard.Models;

namespace ClientDashboard.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ClientController : Controller
    {
        private ClientDashboardEntities db = new ClientDashboardEntities();

        //
        // GET: /Client/

        public ActionResult Index()
        {
            return View(db.Clients.ToList());
        }

        //
        // GET: /Client/Details/5

        public ActionResult Details(int id = 0)
        {
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        //
        // GET: /Client/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Client/Create

        [HttpPost]
        public ActionResult Create(Client client, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                    try
                    {
                        string path = Path.Combine(Server.MapPath("~/Images/"), Path.GetFileName(file.FileName));
                        if (System.IO.File.Exists(path))
                            System.IO.File.Delete(path);
                        file.SaveAs(path);
                        client.ImagePath = "/Images/" + Path.GetFileName(file.FileName);
                    }
                    catch (Exception ex)
                    {
                        // ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                else
                    client.ImagePath = client.ImagePath;
                db.Clients.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(client);
        }

        //
        // GET: /Client/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        //
        // POST: /Client/Edit/5

        [HttpPost]
        public ActionResult Edit(Client client, HttpPostedFileBase file)
        {
           

            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                if (file != null && file.ContentLength > 0)
                    try
                    {
                        string path = Path.Combine(Server.MapPath("~/Images/"), Path.GetFileName(file.FileName));
                        if (System.IO.File.Exists(path))
                            System.IO.File.Delete(path);
                        file.SaveAs(path);
                        client.ImagePath = "/Images/" + Path.GetFileName(file.FileName);
                    }
                    catch (Exception ex)
                    {
                        // ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                else
                {
                    var ImageInDb = db.Clients.Where(s => s.ClientID==client.ClientID).Select(s => s.ImagePath).FirstOrDefault();
                    client.ImagePath = ImageInDb;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        //
        // GET: /Client/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        //
        // POST: /Client/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Client client = db.Clients.Find(id);
            db.Clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ClientDashboard-Integrated/ClientDashboard/ClientDashboard/ClientDashboard/Views/Client/Create.cshtml
@model ClientDashboard.Models.Client

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}


<div class="adminContainer">
@using (Html.BeginForm("Create", "Client", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

 @Html.MvcSiteMap().SiteMapPath()
        <h2>Client - Create
            <div class="backbtn pull-right">
                <span class="glyphicon glyphicon-chevron-left"></span>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </h2>
 <div class="panel panel-default">
  <form class="form-inline">
    <div class="form-group">
        <div class="editor-label col-md-2">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field col-md-4">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
    </div>
    <div class="form-group">
        <div class="editor-label col-md-2">
            @Html.LabelFor(model => model.ImagePath)
        </div>
        <div class="editor-field col-md-4">
            @* @Html.EditorFor(model => model.ImagePath)*@
            <input type="file" name="file" id="file" />

            @Html.ValidationMessageFor(model => model.ImagePath)
        </div>
    </div>
    <div class="form-group">
        <div class="editor-label col-md-2">
            @Html.LabelFor(model => model.Website)
        </div>
        <div class="editor-field col-md-4">
            @Html.EditorFor(model => model.Website)
            @Html.ValidationMessageFor(model => model.Website)
        </div>
    </div>
     <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
     </div>
        </form>
 </div>
}


</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClientDashboard-Integrated/ClientDashboard/ClientDashboard/ClientDashboard/Views/Client/Delete.cshtml
@model ClientDashboard.Models.Client

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Client</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ImagePath)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ImagePath)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Website)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Website)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

ClientDashboard-Integrated/ClientDashboard/ClientDashboard/ClientDashboard/Views/Client/Details.cshtml
@model ClientDashboard.Models.Client

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}
<div class="adminContainer">
    @Html.MvcSiteMap().SiteMapPath()

    <h2>Client - Details
        <div class="backbtn pull-right">
                <span class="glyphicon glyphicon-chevron-left"></span>
                @Html.ActionLink("Back to List", "Index")
        </div>
    </h2>
 <div class="panel panel-default">

    <form class="form-inline">
            <div class="form-group">
                <div class="editor-label col-md-2">
                     @Html.DisplayNameFor(model => model.Name)
                </div>
                 <div class="editor-field col-md-4" style="line-height: 30px">
                    @Html.DisplayFor(model => model.Name)
                </div>
            </div>

   <div class="form-group">
            <div class="editor-label col-md-2">
                @Html.DisplayNameFor(model => model.ImagePath)
            </div>

            <div class="editor-field col-md-4" style="line-height: 30px">
               @* @Html.DisplayFor(model => model.ImagePath)*@
                <img src="@Model.ImagePath"/>
            </div>
    </div>
       <div class="form-group">
            <div class="editor-label col-md-2">
                 @Html.DisplayNameFor(model => model.Website)
            </div>
            <div class="editor-field col-md-4" style="line-height: 30px">
                @Html.DisplayFor(model => model.Website)
            </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
         @Html.ActionLink("Edit", "Edit", new { id=Model.ClientID }, new { @class = " btn btn-default" })
         </div>
    </div>
</form>
<p>
   
    
</p>
</div>
</div>

ClientDashboard-Integrated/ClientDashboard/ClientDashboard/ClientDashboard/Views/Client/Edit.cshtml
@model ClientDashboard.Models.Client

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<div class="adminContainer">

@using (Html.BeginForm("Edit", "Client", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    @Html.MvcSiteMap().SiteMapPath()
        <h2>Client - Edit
            <div class="backbtn pull-right">
                <span class="glyphicon glyphicon-chevron-left"></span>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </h2>

        @Html.HiddenFor(model => model.ClientID)
 <div class="panel panel-default">
    <form class="form-inline">
        <div class="form-group">
            <div class="editor-label col-md-2">
                @Html.LabelFor(model => model.Name)
            </div>
            <div class="editor-field col-md-4">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>
        <div class="form-group">
            <div class="editor-label col-md-2">
                @Html.LabelFor(model => model.ImagePath)
            </div>
            <div class="editor-field col-md-4">
                @*  @Html.DisplayFor(model => model.ImagePath)*@
                 <img src="@Model.ImagePath"/>
                @Html.ValidationMessageFor(model => model.ImagePath)
                <input type="file" name="file" id="file" />

                <span class="EditImageInfo">
                    <span aria-hidden="true" class="glyphicon glyphicon-info-sign"></span>This will replace the existing File.

                </span>
            </div>
        </div>
        <div class="form-group">
            <div class="editor-label col-md-2">
                @Html.LabelFor(model => model.Website)
            </div>
            <div class="editor-field col-md-4">
                @Html.EditorFor(model => model.Website)
                @Html.ValidationMessageFor(model => model.Website)
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>
        </div>
    </form>
    </div>
}


</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClientDashboard-Integrated/ClientDashboard/ClientDashboard/ClientDashboard/Views/Client/Index.cshtml
@model IEnumerable<ClientDashboard.Models.Client>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}
<script>
    $(function () {
        var table = $('#table').dataTable({

            scrollX: true,
            scrollCollapse: true,
            paging: true,
            fixedColumns: true,
        });
    });
</script>
<div class="adminContainer">
    @Html.MvcSiteMap().SiteMapPath()
<h2>Clients
    <span class="createPro ">
        @Html.ActionLink(" ", "Create", new {}, new { @class = " glyphicon glyphicon-plus" })
    </span>
</h2>


    <div class="panel panel-default">

<table id="table" class="Custable Rec">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImagePath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Website)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ImagePath)
                 @*   <img src="@item.ImagePath" style=" max-width:150px;
    max-height:80px;
    width: auto;
    height: auto;"/>
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Website)
                </td>
                <td class="tdLinks">
                    
                        @Html.ActionLink("Edit", "Edit", new { id = item.ClientID }, new { @class = " btn btn-default" })
                        @Html.ActionLink("Details", "Details", new { id = item.ClientID }, new { @class = " btn btn-default" }) @*|
                        @Html.ActionLink("Delete", "Delete", new { id=item.ClientID })*@
                    
                </td>
            </tr>
        }
    </tbody>
</table>
</div>
</div>